json.class Services::Name::TypeResolver.resolve(object)
json.id(object.try(:id))
json.url(object ? polymorphic_url(object, format: :json) : nil)
json.uri object.try(:uri)
json.display(object.try(:display, false))