json.class(object&.respond_to?(:type_of_type) ? object.type_of_type : 'unknown')
json.id(object.try(:id))
json.url(object ? polymorphic_url(object, format: :json) : nil)
json.uri object.try(:uri)
json.display(object.try(:display, false))